spring:
  application:
    name: '@project.name@'
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
info:
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
social-growth-automator:
  config:
    user:
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
    facebook:
      access-token: ${FB_ACCESS_TOKEN}
      account-number: ${FB_ACCOUNT_NUMBER}
